Repository kubeshark/kubeshark, pull requests merged in 2021-09, with the labels that each got.

#258 Fix body size, receive (elapsed time) and timestamps
  agent/pkg/controllers/entries_controller.go
  tap/api/api.go
  tap/extensions/amqp/helpers.go
  tap/extensions/amqp/main.go
  tap/extensions/http/handlers.go
  tap/extensions/http/main.go
  tap/extensions/http/matcher.go
  tap/extensions/kafka/main.go
  tap/extensions/kafka/request.go
  tap/extensions/kafka/response.go
  tap/tcp_reader.go
  tap/tcp_stream.go
  tap/tcp_stream_factory.go
  ui/src/components/EntryDetailed.tsx
Labels: enhancement

#262 Turn `table` and `body` strings to constants and move them to extension API
  tap/api/api.go
  tap/extensions/amqp/helpers.go
  tap/extensions/http/main.go
  tap/extensions/kafka/helpers.go
Labels: enhancement

#266 Temporarily fix the filtering into its original state
  tap/api/api.go
  tap/extensions/http/main.go
  ui/src/components/EntriesList.tsx
Labels: enhancement

#257 Fix the memory exhaustion by optimizing max. AMQP message size and `GOGC`
  .gitignore
  cli/kubernetes/provider.go
  shared/consts.go
  tap/extensions/amqp/main.go
  tap/extensions/amqp/read.go
  tap/extensions/amqp/spec091.go
  tap/extensions/amqp/types.go
  tap/passive_tapper.go
  tap/settings.go
Labels: enhancement

#269 Fix the build error in PR validation
  .github/workflows/pr_validation.yml
Labels: enhancement

#260 Stop the hanging Goroutines by dropping the old, unidentified TCP streams
  tap/api/api.go
  tap/extensions/amqp/main.go
  tap/extensions/http/main.go
  tap/extensions/kafka/main.go
  tap/passive_tapper.go
  tap/settings.go
  tap/stats_tracker.go
  tap/tcp_reader.go
  tap/tcp_stream.go
  tap/tcp_stream_factory.go
Labels: enhancement

#268 Make `ScrollableFeed` virtualized by replacing `react-scrollable-feed` with `react-scrollable-feed-virtualized`
  tap/api/api.go
  tap/extensions/amqp/main.go
  tap/extensions/http/main.go
  tap/extensions/kafka/main.go
  ui/package-lock.json
  ui/package.json
  ui/src/components/EntriesList.tsx
  ui/src/components/EntryListItem/EntryListItem.tsx
  ui/src/components/TrafficPage.tsx
  ui/src/components/style/EntriesList.module.sass
Labels: enhancement

#272 Move `stats_tracker.go` into the extension API and increment `MatchedPairs` from inside the `Emit` method
  tap/api/api.go
  tap/api/stats_tracker.go
  tap/passive_tapper.go
  tap/stats_tracker.go
  tap/tcp_stream.go
  tap/tcp_stream_factory.go
Labels: enhancement

#271 [TRA-3659] Fix rules
  agent/pkg/api/main.go
  agent/pkg/controllers/entries_controller.go
  agent/pkg/models/models.go
  agent/pkg/rules/rulesHTTP.go
  shared/models.go
  tap/api/api.go
  ui/src/components/EntryDetailed.tsx
  ui/src/components/EntryDetailed/EntrySections.tsx
  ui/src/components/EntryDetailed/EntryViewer.tsx
  ui/src/components/EntryListItem/EntryListItem.module.sass
  ui/src/components/EntryListItem/EntryListItem.tsx
Labels: bug, help wanted

#280 Bring back the sensitive data filtering feature
  agent/main.go
  cli/cmd/tapRunner.go
  cli/go.mod
  cli/kubernetes/provider.go
  shared/models.go
  tap/api/api.go
  tap/api/options.go
  tap/api/serializable_regexp.go
  tap/extensions/amqp/main.go
  tap/extensions/http/go.mod
  tap/extensions/http/go.sum
  tap/extensions/http/handlers.go
  tap/extensions/http/main.go
  tap/extensions/http/sensitive_data_cleaner.go
  tap/extensions/kafka/main.go
  tap/passive_tapper.go
  tap/tcp_reader.go
Labels: enhancement

#277 Fix the `OOMKilled` error by calling `debug.FreeOSMemory` periodically
  tap/passive_tapper.go
  tap/settings.go
  tap/tcp_stream_factory.go
Labels: enhancement

#285 Fix the issues related to sensitive data filtering feature
  cli/cmd/tap.go
  cli/cmd/tapRunner.go
  cli/kubernetes/provider.go
  tap/extensions/http/handlers.go
Labels: enhancement

#299 Upgrade `react-scrollable-feed-virtualized` version from `1.4.2` to `1.4.3`
  ui/package-lock.json
  ui/package.json
Labels: enhancement

#300 Don't redact `:authority` pseudo-header field
  tap/extensions/http/sensitive_data_cleaner.go
Labels: enhancement

#302 Don't omit the `Latency` field in `BaseEntryDetails`
  agent/pkg/api/main.go
  tap/api/api.go
  tap/extensions/amqp/main.go
  tap/extensions/http/main.go
  tap/extensions/kafka/main.go
Labels: bug

#290 Add Redis Serialization Protocol support
  tap/extensions/redis/errors.go
  tap/extensions/redis/go.mod
  tap/extensions/redis/handlers.go
  tap/extensions/redis/helpers.go
  tap/extensions/redis/main.go
  tap/extensions/redis/matcher.go
  tap/extensions/redis/read.go
  tap/extensions/redis/structs.go
Labels: enhancement

#298 Omit the `RESPONSE` tab and `elapsedTime` if the `response` is empty
  ui/src/components/EntryDetailed.tsx
  ui/src/components/EntryDetailed/EntryViewer.tsx
Labels: enhancement

#303 Omit the `RULES` tab if the policy rules feature is inactive
  agent/pkg/api/main.go
  agent/pkg/controllers/entries_controller.go
  agent/pkg/models/models.go
  agent/pkg/rules/rulesHTTP.go
  cli/kubernetes/provider.go
  tap/api/api.go
  ui/src/App.tsx
  ui/src/components/EntryDetailed.tsx
  ui/src/components/EntryDetailed/EntrySections.tsx
  ui/src/components/EntryDetailed/EntryViewer.tsx
Labels: enhancement

#307 Fix the typo in `protocolAbbreviation` field of `MizuEntry`
  tap/api/api.go
Labels: bug

#308 Fix a `500` error caused by an interface conversion in Redis
  tap/extensions/redis/helpers.go
  tap/extensions/redis/main.go
Labels: bug

#310 Watch the tapper pod after starting it
  cli/cmd/tapRunner.go
Labels: enhancement

#309 Start the tapper after the API server is ready
  agent/main.go
  agent/pkg/utils/socket_client.go
  cli/cmd/tapRunner.go
Labels: enhancement
