Repository kubeshark/kubeshark, pull requests merged in 2022-11, with the labels that each got.

#1224 Fix `fatal error: concurrent map read and map write`
  tap/tcp_assembler.go
Labels: bug, agent/tapper

#1240 :rotating_light: Delete the acceptance tests
  .github/workflows/acceptance_tests.yml
  .github/workflows/static_code_analysis.yml
  Makefile
  acceptanceTests/.snyk
  acceptanceTests/Makefile
  acceptanceTests/config_test.go
  acceptanceTests/create_user.sh
  acceptanceTests/cypress.config.js
  acceptanceTests/cypress/e2e/testHelpers/StatusBarHelper.js
  acceptanceTests/cypress/e2e/testHelpers/TrafficHelper.js
  acceptanceTests/cypress/e2e/tests/GuiPort.js
  acceptanceTests/cypress/e2e/tests/IgnoredUserAgents.js
  acceptanceTests/cypress/e2e/tests/MultipleNamespaces.js
  acceptanceTests/cypress/e2e/tests/NoRedact.js
  acceptanceTests/cypress/e2e/tests/Rabbit.js
  acceptanceTests/cypress/e2e/tests/Redact.js
  acceptanceTests/cypress/e2e/tests/Redis.js
  acceptanceTests/cypress/e2e/tests/Regex.js
  acceptanceTests/cypress/e2e/tests/UiTest.js
  acceptanceTests/extensions_test.go
  acceptanceTests/go.mod
  acceptanceTests/go.sum
  acceptanceTests/logs_test.go
  acceptanceTests/setup.sh
  acceptanceTests/tap_test.go
  acceptanceTests/testsUtils.go
  docs/TESTING.md
Labels: tests, CI

#1250 :books: Move the images under `assets` directory to `kubeshark/assets` repo
  README.md
  assets/kubeshark-example.png
  assets/kubeshark-logo.svg
  assets/kubeshark-ui-clean.png
  assets/kubeshark-ui.png
  assets/validation-example1.png
  assets/validation-example2.png
  docs/CONTRIBUTING.md
  docs/TESTING.md
Labels: documentation

#1251 :books: Move `CODE_OF_CONDUCT.md` and `CONTRIBUTING.md` to project root
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  README.md
  docs/CHANGELOG.md
  docs/CODEOWNERS
  docs/TESTING.md
Labels: documentation

#1255 :sparkles: Use `github.com/rs/zerolog` for logging
  cmd/check.go
  cmd/check/imagePullInCluster.go
  cmd/check/kubernetesApi.go
  cmd/check/kubernetesPermissions.go
  cmd/check/kubernetesResources.go
  cmd/check/kubernetesVersion.go
  cmd/check/serverConnection.go
  cmd/checkRunner.go
  cmd/common.go
  cmd/config.go
  cmd/goUtils/funcWrappers.go
  cmd/logs.go
  cmd/root.go
  cmd/tap.go
  cmd/tapRunner.go
  cmd/version.go
  cmd/view.go
  cmd/viewRunner.go
  config/config.go
  config/configStruct.go
  config/configStructs/tapConfig.go
  go.mod
  go.sum
  internal/connect/hub.go
  kubernetes/kubesharkTapperSyncer.go
  kubernetes/provider.go
  kubernetes/proxy.go
  kubernetes/watch.go
  kubeshark.go
  kubeshark/fsUtils/kubesharkLogsUtils.go
  kubeshark/fsUtils/zipUtils.go
  kubeshark/version/versionCheck.go
  resources/cleanResources.go
  resources/createResources.go
  utils/browser.go
  utils/wait.go
Labels: CLI
