Repository kubeshark/kubeshark, pull requests merged in 2022-04, with the labels that each got.

#959 Adding resolved prop to service map node
  agent/pkg/controllers/service_map_controller_test.go
  agent/pkg/servicemap/models.go
  agent/pkg/servicemap/servicemap.go
Labels: agent/api-server

#960 TRA-4442 Improve UI performance
  ui-common/src/components/TrafficViewer/EntriesList.tsx
  ui-common/src/components/TrafficViewer/TrafficViewer.tsx
  ui/package.json
Labels: web-ui

#967 Add conditional Go lint validation to CI
  .github/workflows/static_code_analysis.yml
Labels: CI

#962 Ui/TRA-4461_service-map-&-OAS---GUI-changes
  ui-common/src/components/OasModal/OasModal.tsx
  ui-common/src/components/UI/InformationIcon.tsx
  ui-common/src/components/UI/assets/info.svg
  ui-common/src/components/UI/style/InformationIcon.module.sass
  ui-common/src/components/UI/style/StatusBar.module.sass
  ui/src/components/Pages/TrafficPage/TrafficPage.tsx
Labels: web-ui

#969 Fixed golint modified files
  .github/workflows/static_code_analysis.yml
Labels: CI

#970 Handle `reflect.TypeOf` returning `nil` case
  tap/extensions/http/helpers.go
Labels: bug, agent/api-server, proto/http

#961 Refactor ws
  agent/main.go
  agent/pkg/api/entry_streamer_socket_connector.go
  agent/pkg/api/socket_data_streamer.go
  agent/pkg/api/socket_routes.go
  agent/pkg/api/socket_server_handlers.go
  agent/pkg/dependency/type_names.go
Labels: agent/api-server

#971 Fixed golint strings.Title is deprecated error
  tap/extensions/kafka/go.mod
  tap/extensions/kafka/go.sum
  tap/extensions/kafka/helpers.go
Labels: proto/kafka, CI

#966 Ui/Service-map-split-to-ui-common
  ui-common/package.json
  ui-common/src/components/ServiceMapModal/ServiceMapModal.module.sass
  ui-common/src/components/ServiceMapModal/ServiceMapModal.tsx
  ui-common/src/components/ServiceMapModal/ServiceMapModalTypes.ts
  ui-common/src/components/ServiceMapModal/ServiceMapOptions.ts
  ui-common/src/components/ServiceMapModal/assets/close.svg
  ui-common/src/components/ServiceMapModal/assets/refresh.svg
  ui-common/src/components/ServiceMapModal/assets/spinner.svg
  ui-common/src/components/UI/NoDataMessage.tsx
  ui-common/src/components/UI/Radio.tsx
  ui-common/src/components/UI/SelectList.tsx
  ui-common/src/components/UI/assets/dotted-circle.svg
  ui-common/src/components/UI/index.ts
  ui-common/src/components/UI/style/NoDataMessage.module.sass
  ui-common/src/components/UI/style/SelectList.module.sass
  ui-common/src/components/UI/style/Spinner.module.sass
  ui-common/src/helpers/Utils.ts
  ui-common/src/index.tsx
  ui/src/App.tsx
  ui/src/components/AnalyzeButton/AnalyzeButton.tsx
  ui/src/components/ServiceMapModal/ServiceMapModal.sass
  ui/src/components/ServiceMapModal/ServiceMapModal.tsx
  ui/src/components/ServiceMapModal/ServiceMapOptions.ts
  ui/src/components/style/Spinner.module.sass
  ui/src/configs/shortcutsKeyboard.ts
  ui/src/helpers/api.js
  ui/src/helpers/routes.ts
  ui/src/hooks/useKeyPress.ts
  ui/src/recoil/entPage/atom.ts
  ui/src/recoil/entPage/index.ts
  ui/src/recoil/entries/atom.ts
  ui/src/recoil/entries/index.ts
  ui/src/recoil/tappingStatus/atom.ts
  ui/src/recoil/tappingStatus/details.ts
  ui/src/recoil/tappingStatus/index.ts
Labels: web-ui

#974 TRA-4410 Display `namespace` field in the UI
  tap/api/api.go
  ui-common/src/components/TrafficViewer/EntryDetailed.tsx
  ui-common/src/components/TrafficViewer/EntryListItem/EntryListItem.tsx
Labels: agent/api-server, web-ui

#982 Fix the unit tests of protocol extensions
  tap/extensions/amqp/Makefile
  tap/extensions/http/Makefile
  tap/extensions/kafka/Makefile
  tap/extensions/redis/Makefile
Labels: tests, CI

#985 TRA-4474 Fix WS error when switching from settings to traffic viewer
  ui-common/src/components/TrafficViewer/TrafficViewer.tsx
Labels: web-ui

#986 Fixed service map unresolved bug
  agent/go.mod
  agent/go.sum
  agent/pkg/servicemap/servicemap.go
Labels: bug, agent/api-server

#987 TRA-4477 FE holds limit of 10000 entries
  ui-common/src/components/TrafficViewer/EntriesList.tsx
Labels: web-ui

#992 Use author instead of committer in slack alerts
  .github/workflows/acceptance_tests.yml
Labels: CI

#998 Fix the unit tests of protocol extensions
  tap/extensions/amqp/Makefile
  tap/extensions/http/Makefile
  tap/extensions/kafka/Makefile
  tap/extensions/redis/Makefile
Labels: tests, CI

#1000 Fix acceptance tests entry id is string and not number
  acceptanceTests/cypress/integration/testHelpers/TrafficHelper.js
  acceptanceTests/cypress/integration/tests/IgnoredUserAgents.js
  acceptanceTests/cypress/integration/tests/UiTest.js
Labels: tests

#979 Increase the OOM risk in exchange of less idle CPU usage
  tap/settings.go
  tap/tcp_streams_map.go
Labels: agent/tapper

#1003 Fix the acceptance tests `noMoreDataTop` issue
  Dockerfile
  agent/go.mod
  agent/go.sum
  cli/go.mod
  cli/go.sum
  ui-common/src/components/TrafficViewer/EntriesList.tsx
Labels: web-ui, tests, basenine

#1010 TRA-4492 FE miss WS entries
  ui-common/src/components/TrafficViewer/EntriesList.tsx
Labels: web-ui

#1008 TRA-4494 Remove all non-functional `OutboundLink` code that was providing `/status/recentTLSLinks` endpoint
  agent/go.mod
  agent/go.sum
  agent/pkg/controllers/status_controller.go
  agent/pkg/models/models.go
  agent/pkg/providers/status_provider.go
  agent/pkg/routes/status_routes.go
  shared/models.go
  tap/go.mod
  tap/go.sum
  tap/net_utils.go
  tap/outboundlinks.go
  tap/passive_tapper.go
  tap/tcp_reader.go
  tap/tcp_stream_factory.go
Labels: bug

#1016 Run unit tests when tap/api changes
  .github/workflows/test.yml
  tap/api/api.go
  tap/extensions/amqp/Makefile
  tap/extensions/http/Makefile
  tap/extensions/kafka/Makefile
  tap/extensions/redis/Makefile
Labels: tests, CI

#1019 Upgrade Basenine to `0.7.3`
  Dockerfile
  agent/go.mod
  agent/go.sum
  cli/go.mod
  cli/go.sum
Labels: basenine

#1020 `GetEntry` unmarshaling error indicates an error message sent by the database server
  agent/pkg/entries/entries_provider.go
Labels: bug

#1029 Fixed tapper socket error on failure
  agent/main.go
Labels: bug, agent/tapper

#1030 TRA-4524 Started listening label
  ui-common/src/components/TrafficViewer/EntriesList.tsx
Labels: web-ui

#1031 Fix the CLI build error for Windows target
  cli/Makefile
  cli/config/configStructs/tapConfig.go
  cli/go.mod
  cli/go.sum
Labels: bug, CLI, CI

#1038 Fix: websocket timeouts when many traffic etries sent
  agent/pkg/api/socket_routes.go
Labels: bug, agent/api-server

#1037 Fixed OAS showing unresolved services
  agent/pkg/oas/oas_generator.go
Labels: bug, agent/api-server

#1039 Add docker buildx acceptance tests image build
  .github/workflows/acceptance_tests.yml
  .github/workflows/acceptance_tests_on_pr.yml
  acceptanceTests/setup.sh
  acceptanceTests/testsUtils.go
Labels: tests, CI

#1026 Refactor `tap` module to achieve synchronously closing other protocol dissectors upon identification
  shared/consts.go
  shared/kubernetes/provider.go
  tap/api/api.go
  tap/api/go.mod
  tap/cleaner.go
  tap/extensions/amqp/go.mod
  tap/extensions/amqp/main.go
  tap/extensions/amqp/main_test.go
  tap/extensions/amqp/tcp_reader_mock_test.go
  tap/extensions/amqp/tcp_stream_mock_test.go
  tap/extensions/http/go.mod
  tap/extensions/http/handlers.go
  tap/extensions/http/main.go
  tap/extensions/http/main_test.go
  tap/extensions/http/tcp_reader_mock_test.go
  tap/extensions/http/tcp_stream_mock_test.go
  tap/extensions/kafka/go.mod
  tap/extensions/kafka/main.go
  tap/extensions/kafka/main_test.go
  tap/extensions/kafka/request.go
  tap/extensions/kafka/response.go
  tap/extensions/kafka/tcp_reader_mock_test.go
  tap/extensions/kafka/tcp_stream_mock_test.go
  tap/extensions/redis/go.mod
  tap/extensions/redis/handlers.go
  tap/extensions/redis/main.go
  tap/extensions/redis/main_test.go
  tap/extensions/redis/tcp_reader_mock_test.go
  tap/extensions/redis/tcp_stream_mock_test.go
  tap/go.mod
  tap/go.sum
  tap/passive_tapper.go
  tap/settings.go
  tap/tcp_assembler.go
  tap/tcp_reader.go
  tap/tcp_reader_data_msg.go
  tap/tcp_reassembly_stream.go
  tap/tcp_stream.go
  tap/tcp_stream_factory.go
  tap/tcp_streams_map.go
  tap/tlstapper/chunk.go
  tap/tlstapper/tls_poller.go
  tap/tlstapper/tls_reader.go
Labels: enhancement, agent/tapper, proto/http, proto/http2, proto/grpc, proto/kafka, proto/amqp, proto/redis, eBPF
